CC= arm-none-eabi-gcc
CFLAGS = -I$(LIBPI)/.. -I. -Wall -Og -nostdlib -nostartfiles -ffreestanding

#libpi.small
LIBPI = libpi-mine

SRC = bootloader.c
OBJS = $(SRC:.c=.o)

all : libpi kernel.img

start.o : start.s
	arm-none-eabi-as start.s -o start.o

libpi :
	@make -C $(LIBPI)

kernel.img : memmap start.o $(OBJS)
	arm-none-eabi-ld start.o $(OBJS) $(LIBPI)/libpi.a -T memmap -o bootloader.elf
	arm-none-eabi-objdump -D bootloader.elf > bootloader.list
	arm-none-eabi-objcopy bootloader.elf -O binary kernel.img

clean :
	rm -f *.o *.bin *.elf *.list *.img *~ Makefile.bak
	make -C $(LIBPI) clean

depend:
	makedepend -I$(LIBPI)/.. *.[ch]

# DO NOT DELETE
